<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Spotify from '$lib/components/spotify.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;
</script>

<Post>
  <article slot="post_content">
    <h2 id="foreword"><a href="#foreword">🚀 Foreword</a></h2>
    <InfoBox statusType="tip" statusName="閱前導覽">
      <p>
        Welcome! <br />
        這裡會放放平常本業的踩坑紀錄及新發現的酷東西
        <br />
        除此之外還會放放吃吃ㄏㄏ跑跑跳跳聽聽畫畫的紀錄，繞去其他頁籤看看吧
        <br />
        可以利用首頁上面的🔍或旁邊的
        <kbd>tag</kbd>
        🏷️找找有沒有能幫上忙的東西
        <br />
      </p>
    </InfoBox>
  </article>
</Post>
