<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  import Spotify from '$lib/components/spotify.svelte';
  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <InfoBox statusType="tip" statusName="起因">
      <p>
        在YT蝦晃的時候，被這一小段
        <a href="https://www.youtube.com/watch?v=gidpDOWNLpI" rel="external">插入曲</a>
        給吸引到
      </p>
    </InfoBox>
    <h2 id="ting1-ting1-kan4-ting1-kan4-kan4"><a href="#ting1-ting1-kan4-ting1-kan4-kan4">聽聽看，聽看看</a></h2>
    <Youtube id="dMGhEiYRoZE" />

    <h2 id="arujnon"><a href="#arujnon">アルジャーノン(阿爾吉儂)</a></h2>
    <p>
      アルジャーノン(阿爾吉儂) 是為電視劇『夕暮れに、手をつなぐ』(意思是夕暮時分牽起手)
      所做的主題曲，而命名的靈感取至美國作家丹尼爾·凱斯著作《獻給阿爾吉儂的花束》🌻，正巧也有在2015年被翻拍成日劇，由帥到掉渣的山下智久擔當男主角
      <br />
    </p>
    <ImgZoom
      src="/music_coloring/algernon/algernon.jpg"
      alt="Example1"
      class="h-full object-cover"
      width="550"
      height="309">
      Photo by <a href="https://www.tbs.co.jp/algernon2015/" target="_blank">アルジャーノンに花束を</a>
      on
      <a href="https://www.tbs.co.jp/" target="_blank">TBS Japan</a>
    </ImgZoom>

    <p>
      作品中的阿爾吉儂其實是一隻被注射實驗藥物而變聰明的老鼠🐁，而主角則是一位天生的智能障礙者，因緣際會下被選中為人體實驗品而被注射相同的藥物，這也使得他一夕之間成為智商超群的天才。
      <br />
    </p>
    <p>
      不過心靈層面趕不上智商躍升的後果就是他比以前更不信任他人，此時他也發現藥物的副作用...
      <br />
      除了智商退化外甚至不知還剩幾日可活，而這本《獻給阿爾吉儂的花束》🌻 其實本身就是一個實驗記錄
      <br />
    </p>
    <ImgZoom
      src="/music_coloring/algernon/FlowersForAlgernon.jpg"
      alt="Example1"
      class="h-full object-cover"
      width="263"
      height="380">
      初版封面 of <a
        href="https://zh.wikipedia.org/zh-tw/%E7%8D%BB%E7%B5%A6%E9%98%BF%E7%88%BE%E5%90%89%E5%84%82%E7%9A%84%E8%8A%B1%E6%9D%9F"
        target="_blank">
        Flowers For Algernon
      </a>
    </ImgZoom>

    <blockquote>
      <p>
        <b style="color:#4c8181">
          刻畫著從一開始的錯字連篇，一天天演變成複雜艱深的詞彙，歷經錯綜複雜的情緒糾結最後再退回當初童稚的語氣...
        </b>
      </p>
    </blockquote>
    <h2 id="dian3-ping2"><a href="#dian3-ping2">點評</a></h2>
    <p>
      <b style="color:#4c8181">即便聽了很多人的解析，我還是很想知道身為作詞/曲本身的n-buna的創作初衷</b>
      <br />
      以下節錄了他的看法
      <br />
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code>{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">箱の中に迷路がある。</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">途方もなく複雑に入り組んだ道を貴方は歩いていく。</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">壁の向こう側に何かがあると信じて止まらず</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">時折道に迷いながらもただ出口へと進み続ける。</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">その姿が僕には少し眩しい。</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">そういう曲です。</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>
      意思大概是
      <br />
      這是一個處在
      <b style="color:#4c8181">箱庭的迷宮</b>
      <br />
      你走在一條極其複雜和
      <b style="color:#4c8181">錯綜複雜的路上</b>
      <br />
      <br />
      我無法停止相信牆的另一邊有東西
      <br />
      即便偶爾會迷路，我還是
      <b style="color:#4c8181">持續的向出口前進</b>
      <br />
      而這樣的身姿似乎對我太過於耀眼
      <br />
      <br />
      就是這麼一首歌。
      <br />
    </p>
    <h2 id="xiao3-jie2"><a href="#xiao3-jie2">小結</a></h2>
    <blockquote>
      <p>
        作者在《獻給阿爾吉儂的花束》一書結尾，拋出了一個從未有人釐清的問題：
        <code class="inline-code-block">智慧與幸福能否兼得？</code>
        <br />
        到底是追求平凡的幸福還是承擔擁有智慧後的責任，或許就像n-buna說的，我們都在這
        <b style="color:#dd3e43">錯綜複雜的情緒</b>
        中不斷糾結著。
        <br />
        不過回頭看看，說不定就會發現愛你的人
        <br />
        所以不管有甚麼困難，平靜地等待吧，
        <b style="color:#dd3e43">慢慢的改變，就像那緩緩膨脹的麵包</b>
        <br />
        這就是為甚麼我們能
        <b style="color:#dd3e43">繼續向前邁進</b>
        而不用擔心這
        <b style="color:#dd3e43">長長的迷宮</b>
        <br />
      </p>
    </blockquote>
    <h2 id="zhu3-wei3-jia1-ma3-shi2-jian4"><a href="#zhu3-wei3-jia1-ma3-shi2-jian4">主委加碼時間</a></h2>
    <h3 id="youtube"><a href="#youtube">Youtube</a></h3>
    <InfoBox statusType="info" statusName="小提醒">
      <p>
        YT有時候會因瀏覽權限的關係導致只能在YT上才能觀看...
        <br />
        遇到這種時候就動動手指點擊
        <u>在YouTube上觀看</u>
      </p>
    </InfoBox>
    <Youtube id="5v5CjaTDuOk" />

    <h3 id="spotify"><a href="#spotify">Spotify</a></h3>
    <Spotify id="0L1E2JmrZk6QU9261PtJWQ" />

    <p>是時候該Say goodbye了 👋 感謝你的收看</p>
  </article>
</Post>
