<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="foreword"><a href="#foreword">🎶 Foreword</a></h2>
    <InfoBox statusType="tip">
      <p>
        ✨Welcome! <br />
        這裡會分享
        <span class="spoiler">我主觀認為</span>
        好聽的音樂及本人拙劣的繪畫記錄
        <br />
        除此之外還有放放吃吃及技術類的相關文章，繞去其他頁籤看看吧
        <br />
        可以利用首頁上面的🔍或旁邊的
        <kbd>tag</kbd>
        🏷️找找有沒有能幫上忙的東西
        <br />
      </p>
    </InfoBox>
    <h2 id="qi3-yin1"><a href="#qi3-yin1">起因</a></h2>
    <blockquote>
      <p>
        在22年中，我買了人生第一台iPad Pro🎉
        <br />
        為了努力避免
        <b>「買前生產力，買後愛奇藝」</b>
        ，對抗懶惰蟲
        <br />
        <ImgZoom src="/music_coloring/ipad_use.jpg" alt="" class="h-full object-cover">
          本分析擷取至 <a href="https://www.chinatimes.com/realtimenews/20230221003839-260405?chdtv" target="_blank">
            網路溫度計
          </a>
        </ImgZoom>
        我買了
        <a href="https://procreate.com/" target="_blank">Procreate</a>
        這個繪圖軟體，並設定了
        <kbd>本周最常聽的音樂</kbd>
        及
        <kbd>近期發生趣事</kbd>
        這兩個主題，嘗試把他們畫出來
        <br />
      </p>
      <blockquote>
        <p>
          繪畫本身可以把我
          <code class="inline-code-block">從一個狀態轉移到另一個狀態</code>
          進而達到
          <kbd>休息</kbd>
          的效果
          <br />
          所以如果沒意外，我會想一直持續畫下去
          <span class="spoiler">但就請各位的眼睛多擔待了</span>
        </p>
      </blockquote>
    </blockquote>
    <ImgZoom src="/music_coloring/paint.jpg" alt="我警告過囉~" class="h-full object-cover" width="500" />

    <InfoBox statusType="caution" statusName="警告">
      <p>
        如果你看到這了，就代表你是不聽勸的孩子🤣
        <br />
        那就來吧 ! 🚀
        <br />
      </p>
      <h3>
        聽聽看🎧聽看看👀
        <br />
      </h3>
    </InfoBox>
    <h2 id="lie4-biao3"><a href="#lie4-biao3">列表</a></h2>
    <h3 id="arujnon"><a href="#arujnon">アルジャーノン</a></h3>
    <h4>
      <a href="/music_coloring/algernon"><b style="color:#4c8181">アルジャーノン | 介紹</b></a>
      👉
    </h4>
    <ImgZoom src="/music_coloring/algernon/cover.png" alt="アルジャーノン" class="h-full object-cover" width="500" />
  </article>
</Post>
